### ISSUE TITLE
[Suggestion] Support for Group

### ISSUE THREAD

**Issue by jygastaud** [alebeck/boring#5]
Hi,

Thanks for your work on that tool.

That issue is a suggestion/idea for supporting group of forward rules, something like

```toml
[[tunnels]]
# The group declared
name = "example"
host = "forward.XXXX"
[[tunnel]]
# forward 1
local = "9444"
remote = "XXXX:443"
[[tunnel]]
# forward 2
local = "9443"
remote = "XXXX:443"
```

With that kind of config the `boring open example` command could generate / open many connexions at once

```
➜ boring list
Status  Name       Local      Remote                                                                                                   Via
open    example   9443   -> XXXX:443    forward.XXXX
open    example   9444   -> XXXX:443    forward.XXXX
```
